import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { createInterface } from 'readline';
import { getConfigDir, getConfigPath } from './config.js';

const DEFAULT_API_URL = 'https://api.easy-node.xyz';
const DEFAULT_MAX_PAYMENT = '100';

interface SetupAnswers {
  privateKey: string;
  apiUrl: string;
  maxPayment: string;
}

function prompt(rl: ReturnType<typeof createInterface>, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

function isValidPrivateKey(key: string): boolean {
  return /^0x[a-fA-F0-9]{64}$/.test(key);
}

export async function runSetup(): Promise<void> {
  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log('\n=== Easy Node MCP x402 Setup ===\n');
  console.log(
    'This will configure your wallet for purchasing VPS/Node products with USDC on Base.\n'
  );

  const answers: SetupAnswers = {
    privateKey: '',
    apiUrl: DEFAULT_API_URL,
    maxPayment: DEFAULT_MAX_PAYMENT,
  };

  // Private key (required)
  while (!answers.privateKey) {
    const key = await prompt(rl, 'Enter your wallet private key (0x...): ');
    if (!key) {
      console.log('Private key is required.');
      continue;
    }
    if (!isValidPrivateKey(key)) {
      console.log('Invalid private key format. Must be 0x followed by 64 hex characters.');
      continue;
    }
    answers.privateKey = key;
  }

  // API URL (optional)
  const apiUrl = await prompt(rl, `API URL [${DEFAULT_API_URL}]: `);
  if (apiUrl) {
    answers.apiUrl = apiUrl;
  }

  // Max payment (optional)
  const maxPayment = await prompt(
    rl,
    `Max payment per transaction in USDC [${DEFAULT_MAX_PAYMENT}]: `
  );
  if (maxPayment) {
    const parsed = parseFloat(maxPayment);
    if (isNaN(parsed) || parsed <= 0) {
      console.log('Invalid amount. Using default.');
    } else {
      answers.maxPayment = maxPayment;
    }
  }

  rl.close();

  // Save configuration
  const configDir = getConfigDir();
  const configPath = getConfigPath();

  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }

  const envContent = `# Easy Node MCP x402 Configuration
# Generated by: npx @easynodexyz/mcp-x402 setup

EASYNODE_PRIVATE_KEY=${answers.privateKey}
EASYNODE_API_URL=${answers.apiUrl}
EASYNODE_MAX_PAYMENT=${answers.maxPayment}
`;

  writeFileSync(configPath, envContent, { mode: 0o600 });

  console.log(`\nConfiguration saved to: ${configPath}`);
  console.log('\n=== Claude Desktop Configuration ===\n');
  console.log('Add this to your claude_desktop_config.json:\n');

  const claudeConfig = {
    mcpServers: {
      'easy-node': {
        command: 'npx',
        args: ['@easynodexyz/mcp-x402'],
      },
    },
  };

  console.log(JSON.stringify(claudeConfig, null, 2));

  console.log('\nConfig file locations:');
  console.log('  macOS: ~/Library/Application Support/Claude/claude_desktop_config.json');
  console.log('  Windows: %APPDATA%\\Claude\\claude_desktop_config.json');
  console.log('  Linux: ~/.config/Claude/claude_desktop_config.json');

  console.log('\nSetup complete! Restart Claude Desktop to use the easy-node MCP server.\n');
}
